apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: granite-chat
  namespace: rhel-ai-chat
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/display-name: "IBM Granite 8B Lab v1"
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    securityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    containers:
      - name: kserve-container
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-cpu-x86-runtime
      storageUri: oci://registry.redhat.io/rhelai1/modelcar-granite-8b-lab-v1:1.4.0
      resources:
        requests:
          cpu: '4'
          memory: 12Gi
        limits:
          cpu: '8'
          memory: 24Gi
