apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: granite-chat
  namespace: rhel-ai-chat
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/display-name: "Facebook OPT-125M"
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-cpu-x86-runtime
      storageUri: hf://facebook/opt-125m
      resources:
        requests:
          cpu: '1'
          memory: 2Gi
        limits:
          cpu: '2'
          memory: 4Gi
      env:
      - name: VLLM_SKIP_WARMUP
        value: "true"
      - name: VLLM_CPU_KVCACHE_SPACE
        value: "2"
      args:
      - --max-model-len=2048
      - --max-num-seqs=4
