apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: granite-chat
  namespace: rhel-ai-chat
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/display-name: "SmolLM3 3B"
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-cpu-x86-runtime
      storageUri: oci://registry.redhat.io/rhelai1/modelcar-smollm3-3b:1.5-1754500365
      resources:
        requests:
          cpu: '2'
          memory: 6Gi
        limits:
          cpu: '4'
          memory: 12Gi
      env:
      - name: VLLM_SKIP_WARMUP
        value: "true"
      - name: VLLM_CPU_KVCACHE_SPACE
        value: "4"
      args:
      - --max-model-len=4096
      - --max-num-seqs=8
